<?php
namespace Lmap\StarTrackShipping\Test\Model\ResourceModel;

use Lmap\StarTrackShipping\Model\ResourceModel\StarTrackRates;
use PHPUnit\Framework\TestCase;

class StarTrackRatesTest extends \PHPUnit\Framework\TestCase
{
    // \PHPUnit_Framework_TestCase
    // issue occured while running unit test "magento 2 PHPUnit_Framework_TestCase not found" .Solution in
    // https://magento.stackexchange.com/questions/262824/phpunit-framework-testcase-not-found

    private $startrackrate;

    protected function setUp()
    {
        // In this setUp function assign instance of class under test to our property
        parent::setUp(); // TODO: Change the autogenerated stub
    }


}



